name: Build & Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    uses: nanite/workflows/.github/workflows/standard-release.yml@v1
    with:
      java-version: 17
      changelog-file: "./CHANGELOG.md"
      curse-publish-task: "publishMods"
      release-files: ./+(forge|fabric)/build/libs/*.jar
    secrets:
      nanite-token: ${{ secrets.NANITE_DEPLOY }}
      curse-token: ${{ secrets.CURSE_DEPLOY }}